### ISSUE TITLE
Get user data

### ISSUE THREAD

**Issue by jcastro** [ckuburlis/homebridge-tado#1]
Is there an 'easy' way to get the required ID? I already have a Tado account (user and password) but need to intercept the ID

Thanks!

**Comment by ckuburlis** [comment]
Hey, I've just updated the [readme](https://github.com/ckuburlis/homebridge-tado/blob/master/README.md). Check it out and tell me if you have any issues :)

At the moment not all the Siri commands work so while you can set the temperature by saying something like "Set the air-con to 25º" you can't say "Turn the air-con [on/off]"... Currently the only way to turn it off is by adding it to a scene and changing the mode or using a home-kit friendly app.

**Comment by jcastro** [comment]
Thanks a lot! I was able to get the homeID now :)

One question, would it be possible to support the heat mode? I'm currently running homebridge on my Pi2 and on my iPhone I setup the thermostat by using Elgato Eve. I can see temperatures (though all referenced to cooling system) but I can't control or even get info about it with Siri

Thanks!

**Comment by ckuburlis** [comment]
Hey, try updating the plugin to version 0.1.0+ there's been a lot of updates to make things work.
So far the only thing I can't seem to get Siri to do it change mode/turn the aircon or thermostat on/off directly.

I can use a scene to turn it on/off or tell Siri to turn the thermostat to a specific temperature but for some reason it doesn't find a thermostat when you say 'turn on the [aircon/thermostat]' - I'm not sure if this is a problem on my side as people with the nest plugin seem to be having the same problem & everything seems to be setup in home kit.

Currently the internal temperature and humidity sensor do work with Siri but you have to say something like 'What's the temperature inside' or 'What's the humidity in [room name]'.

As for controlling the different modes (heat/cool/auto) at the moment the plugin only supports cooling due to my aircon only doing cooling at the moment so I only send the cooling mode for all commands. I'll have a go at it, but there's no way for me to test it.

**Comment by jcastro** [comment]
Yes! I can now at least get info from Siri (temperature, humidity, etc). Thanks!

Let me know if I can help you with something to work out the heat-thermostat version! (I don't have the cooling one, actually)

**Comment by ckuburlis** [comment]
Peteakalas modified the plugin to do just that, you may want to check out https://github.com/peteakalad/homebridge-tadoheating :)

**Comment by jcastro** [comment]
that's great! thanks!
