### ISSUE TITLE
Only turning off The A/C works. 

### ISSUE THREAD

**Issue by SRv6d** [ckuburlis/homebridge-tado#5]
I can turn off the A/C using this plugin but thats it.
Changing the temperature doesn't work, changing between heating/cooling doesn't work and turning on the A/C doesn't work either.

**Comment by kaiatkins** [comment]
I have the same issue

**Comment by jhavenhill** [comment]
Same issue here. Nothing works except turning off the A/C

**Comment by jhavenhill** [comment]
I fixed this for myself by modifying the request body that is sent in the setTargetTemperature function. My A/C does not have Fan Speed or Swing capabilities (the way it is set up with tado, at least), and manually calling /api/v2/homes/*****/zones/1/overlay returns:

```
{
    "type": "MANUAL",
    "setting": {
        "type": "AIR_CONDITIONING",
        "power": "ON",
        "mode": "COOL",
        "temperature": {
            "celsius": 22.78,
            "fahrenheit": 73
        }
    },
    "termination": {
        "type": "MANUAL",
        "projectedExpiry": null
    }
}
```

So, I simply removed the "swing" and "fanSpeed" entries, and now I am able to turn on my A/C and set the temperature. Perhaps it might be possible to add something like fanSpeed = False and swing = False to the config, for users whose A/Cs don't have these capabilities? Then these entries could be deleted from the request body as necessary.

**Comment by jojoam** [comment]
Same issue here, can  only turn off the AC if it was previously turned on.
Then after the AC is not responding to any control anymore.
Fix from jhavenhill is not working for me.

**Comment by dgaust** [comment]
I also had this problem. I fixed it by editing the index.js file locally to remove "swing": "ON" from the json body (since my tado doesn't have swing support for my AC).

I also changed the termination type from MANUAL to TADO_MODE. This way it will still turn off when I leave the house, or a scheduled time kicks in.

That's a personal choice for me, it would be good to have a setting though.

**Comment by jojoam** [comment]
Hi,

I've removed "swing": "ON" and now it turns on and off correctly.

Thank you for the tip !

Joel

**Comment by morilm** [comment]
After suffering the same issue, I discovered that the index.js file that is installed by default is not the latest one, so the new settings (zones, swing...) doesn't work.

**Comment by jojoam** [comment]
So do you have the latest and solved the issue ?

בברכה,

יואל

**Comment by morilm** [comment]
Yes.   Last index.js support the zones.

      "accessory": "TADO",
      "name": "Salon",
      "homeID": "xxxxx",
      "maxValue": 27,
      "minValue": 18,
      "zone": 1,
      "username": "xxxx",
      "password": "xxxx",
      "useFanSpeed": "LOW",
      "useSwing": false,
      "useFahrenheit": false

**Comment by jojoam** [comment]
Hi,

Thank you again, but it still doesn't work for me.

Which Tado homebridge are you using ? homebridge tado or tadong ?

Could you send me your index.js ? (not the config.js)

Thanks

**Comment by nitaybz** [comment]
Hey Yoel!
this git is for homebridge-tado not tado-ng, so having the last update of homebridge-tado should control your Tado AC smart Control smoothly, let me know if you have specific problems that I can help you with.

index.js can be found in this git codes.

**Comment by jojoam** [comment]
Hi,

Thank you for the update !

I've installed the latest version of homebridge-tado with the updated index.js and now I can control the Tado AC

Although I am able to turn on and change the temperature, I am not able to switch between modes: default is Cooling and the Tado is not responding to Auto and Heat.

Do you have  any suggestion ?

Thank you

**Comment by jojoam** [comment]
Hello,


I have found that when installing homebridge-tado via "npm install -g homebridge" it do not install the latest index.js

When manually installing it, an error messageappears when running homebridge:

"Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new TadoAccessory (/usr/local/lib/node_modules/homebridge-tado/index.js:19:20)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:265:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)"

Reinstalling and updating homebridge and node-persist did not solve the issue.

Joel

**Comment by morilm** [comment]
run 
npm install node-persist 

at the command line to install it

**Comment by nitaybz** [comment]
Make sure you set up your ac correctly for those states.

 Also, the command of the cool Mode is identical to the heat Mode.
You have to setup your config to support your aircon setup. For example: 
Both hot and cold modes on your AC must have the same setting of fanSpeed and swing, if one of the modes has swing and the other don't, it won't work. Make sure they both are the same.

Second, make sure your config support those states, for example: if you can change the fan speed, you must set up for the desired (permanent) speed of the fan in the config:
"useFanSpeed": "AUTO" / "LOW" / "MIDDLE" / "HIGH" - according to your needs(and AC capabilities).
Otherwise just set it to false or remove the line.

Same goes for the swing option:
"swing": "ON" / "OFF" / false

Those have to be correctly configured for both heat and cool.

Make sure "zone" is configured to avoid issues.

If you already did above and problem please consider that too many commands somehow makes it fail but that's either the call receiver part of the device or the connection with the AC, not the plugin itself.
I found them both fail sometimes when testing to much but work smoothly when setting a command for a normal use.
When you are testing the plugin, please compare the commands and look for changes on the Tado app and not on the device itself.

If all still doesn't give you a clue on where to look, please try to send me your log after using those commands, I'll see if there is anything suspicious.

Of course I suggest you to reinstall the plugin or restart home bridge again.

**Comment by nitaybz** [comment]
that's weird... cause it does show in the dependencies, try removing this plugin and node-persist and install it again with sudo:
`sudo npm install -g https://github.com/ckuburlis/homebridge-tado.git`

@ckuburlis Please push the new version to npm

**Comment by jojoam** [comment]
Hi,

Running this command did solve the issue, the plugin is now up to date along with the dependencies.

AC is now correctly responding to mode changes including heating.

Thank you for your patience and kind help.


By the way, I've spoke today with a Tado representative about the time frame of HomeKit integration for Tado AC and they told me that the first product to be HomeKit compliant will be the Tado Heating but not Tado AC

Tado AC won't be due in the near future.

Joel

**Comment by nitaybz** [comment]
yup, I got the same answer from them as well, that's a bummer...
Though I'm glad it worked for you now!
I got 2 new Tado devices recently and I had to make it work properly!

Let me know if any improvements needed.
